### ISSUE TITLE
Aircraft meta data

### ISSUE THREAD

**Issue by MatisseBE** [Sequal32/vrclivetraffic#5]
Hey! 

I was wondering why not all data from FR24's live feed is used. Especially the ADEP, ADES and ATYP are not used, yet clearly provided. FR's information is, at least here in Europe, _way more_ extensive and reliable. 

Thank you for your work on this! It works brilliantly!

**Comment by Sequal32** [comment]
Thanks! Seems like the ADEP/ADES are in IATA format so I'd have to do a small conversion to get those into ICAO format. However, I'm hesitant on adding this in since I doubt controllers IRL would see an aircraft without a FP that has a dep/arrival to it based on where it's flown previously. FlightAware seems to be pretty good for grabbing a flight's data already. That being said, I've integrated the aircraft type into all flights for the next release.

**Comment by MatisseBE** [comment]
Hi! Thanks for the prompt reponse.

In the videos you've posted it is clear that most aircraft have at least some extra meta data, however here in Europe that amount is much less. In the screenshot added below, all grey aicraft have no meta data, all aircraft with a bright blue line have ADES,ADEP and ATYP, yet none have a route (the routes do work, but only very few are available). 

I'm guessing FlightAware is focussed on the US, especially since most routes we do get are to/from the US.

Getting that extra bit of information is always useful for us enthousiasts. Furthermore, it can be used to find and artifically create routes from route-finding APIs such as SimBrief. 

![image](https://user-images.githubusercontent.com/51272243/111593097-e11ecb00-87c9-11eb-90bd-b4df8930ff80.png)

**Comment by Sequal32** [comment]
Hmm I looked up those flights on flightaware and they seem to have the correct data as far as origin and destination goes though maybe it updated after the aircraft landed... It is like you point out though that only US flights really have routes to them. As per your suggestion I've added FR24 origin/destinations into aircraft which don't have the flightaware data and will be pushing an update sometime this week/weekend.

**Comment by Sequal32** [comment]
Release 1.4.0 now adds this feature in!
